// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"true"}},
{"name":"BB_WindowSelector3","status":true,"description":"ウインドウスキンと切り替えるプラグイン。","parameters":{"Variable ID":"1","Window1 Opacity":"192","Window2 Opacity":"255","Window3 Opacity":"192","Window1 OutlineColor":"rgba(0, 0, 0, 0.5)","Window1 OutlineWidth":"4","Window2 OutlineColor":"rgba(0, 0, 0, 0.5)","Window2 OutlineWidth":"4","Window3 OutlineColor":"rgba(0, 0, 0, 0.5)","Window3 OutlineWidth":"4","Window1 DimmerColor":"rgba(0, 0, 0, 0.6)","Window1 DimGradationColor":"rgba(0, 0, 0, 0)","Window2 DimmerColor":"rgba(0, 0, 0, 0.6)","Window2 DimGradationColor":"rgba(0, 0, 0, 0)","Window3 DimmerColor":"rgba(0, 0, 0, 0.6)","Window3 DimGradationColor":"rgba(0, 0, 0, 0)"}},
{"name":"StepEffect","status":true,"description":"ver1.00/足跡などのエフェクトを追加します。","parameters":{"EffectWidth":"48","AnimationSpeed":"8","StepSize":"8","AudibleDistance":"10"}},
{"name":"MessageWindowPopup","status":true,"description":"フキダシウィンドウプラグイン","parameters":{"フォントサイズ":"28","余白":"10","自動設定":"ON","フェイス倍率":"75","ウィンドウ連携":"ON","行間":"4","ウィンドウ透過":"OFF","フォントサイズ増減幅":"12","フォントサイズ上限":"96","フォントサイズ下限":"24"}},
{"name":"PointScroll","status":true,"description":"ver1.00/ポイントや対象を指定して画面をスクロールします。","parameters":{}},
{"name":"PicturePriorityCustomize","status":true,"description":"ピクチャの表示優先度調整プラグイン","parameters":{"上層ピクチャ番号":"101","下層ピクチャ番号":"2","下層ピクチャZ座標":"0"}},
{"name":"TMAnimeLight","status":true,"description":"イベントにアニメーション付きの明かりを表示します。","parameters":{"range":"0.05","defaultZ":"5","frames":"160"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"グリッドサイズ":"48","テストマップID":""}},
{"name":"HalfMove","status":true,"description":"半歩移動プラグイン","parameters":{"8方向移動":"ON","8方向移動スイッチ":"0","イベントすり抜け":"ON","強制中無効":"OFF","角回避":"ON","斜め移動中減速":"OFF","トリガー拡大":"OFF","実歩数調整":"OFF","上半分移動不可地形":"0","上半分移動不可Region":"0","下半分移動不可地形":"0","下半分移動不可Region":"0","右半分移動不可地形":"0","右半分移動不可Region":"0","左半分移動不可地形":"0","左半分移動不可Region":"0","全方向移動不可地形":"0","全方向移動不可Region":"0","イベント複数起動防止":"OFF","イベント位置重複OK":"OFF"}},
{"name":"KMS_WaterMapEffect","status":true,"description":"[v1.1.0] マップに水中エフェクトを適用します。","parameters":{"Flicker image":"KMS_cloud","Wave image":"KMS_wave","Wave opacity":"40","Speed X":"-1.0","Speed Y":"0.1","Auto tone change":"1"}},
{"name":"SAN_AnalogMove","status":true,"description":"アナログムーブ 3.0.2\r\nパーティキャラクターの移動をドット移動に変更します。","parameters":{}},
{"name":"Foreground","status":true,"description":"マップに合わせてスクロールする近景の設定","parameters":{}},
{"name":"TMAnimeLight","status":true,"description":"イベントにアニメーション付きの明かりを表示します。","parameters":{"range":"0.9","defaultZ":"4","frames":"75"}},
{"name":"GALV_MessageSoundEffects","status":true,"description":"Play sound effects when during Show Text event commands.","parameters":{"Delay Time":"3","Default Talk SE":"Cursor1,80,150","Default Confirm SE":"Cursor2,80,150","-----------":"","Quick SE 1":"select04,80,100","Quick SE 2":"","Quick SE 3":"","Quick SE 4":""}}
];
